package DataObjects;

/**
 * Created by Mor on 23/04/2016.
 */
public enum DataKeys {

    COMM_ID,
    DESTINATION_CONTACT_NAME,
    EXTENSION,
    FILE_SIZE,
    FILE_TYPE,
    FILE_PATH_ON_SERVER,
    FILE_PATH_ON_SRC_SD,
    MANAGED_FILE,
    SPECIAL_MEDIA_TYPE,
    MD5,
    SOURCE_ID,
    DESTINATION_ID,
    FILE_PATH,
    INTERNATIONAL_PHONE_NUMBER,
    CALL_RECORD,
    SOURCE_LOCALE,
    SMS_CODE,
    PUSH_TOKEN,
    SOURCE_WITH_EXTENSION,
    IS_REGISTERED,
    IS_REGISTER_SUCCESS,
    IS_UNREGISTER_SUCCESS,
    EVENT_REPORT,
    APP_VERSION,
    MIN_SUPPORTED_VERSION,
    HTML_STRING,
    DEVICE_MODEL,
    ANDROID_VERSION,
    IS_UPDATE_SUCCESS,
    RESPONSE_CODE,
    TABLE,
    COLUMN,
    CONDITION,
    VALUE,
}