package EventObjects;

import java.io.Serializable;

public enum EventType implements Serializable { 
	UPLOAD_SUCCESS,
	UPLOAD_FAILURE,
	DOWNLOAD_SUCCESS,
	DOWNLOAD_FAILURE,	
	LOGIN_FAILURE,
	LOGIN_SUCCESS,
	ISLOGIN_ERROR,
	ISLOGIN_ONLINE,
	ISLOGIN_OFFLINE,
	ISLOGIN_UNREGISTERED,
	DESTINATION_DOWNLOAD_COMPLETE,
	CLIENT_ACTION_FAILURE, 
	CLOSE_APP, 	
	NO_ACTION_REQUIRED,
	DISPLAY_ERROR,
	DISPLAY_MESSAGE,
	RECONNECT_ATTEMPT,
	DISCONNECTED,
	SERVER_PROXY_CREATED,
}
