package EventObjects;

import java.io.Serializable;

public enum EventType implements Serializable { 
	UPLOAD_SUCCESS,
	UPLOAD_FAILURE,
	DOWNLOAD_SUCCESS,
	DOWNLOAD_FAILURE,	
	LOGIN_FAILURE,
	REGISTER_SUCCESS,
	ISREGISTERED_ERROR,
	USER_REGISTERED_TRUE,
	USER_REGISTERED_FALSE,
	DESTINATION_DOWNLOAD_COMPLETE,
	CLIENT_ACTION_FAILURE,
	CLOSE_APP, 	
	NO_ACTION_REQUIRED,
	DISPLAY_ERROR,
	DISPLAY_MESSAGE,
	RECONNECT_ATTEMPT,
	DISCONNECTED,
	CONNECTING,
	CONNECTED,
	SERVER_PROXY_CREATED,
	REFRESH_UI,
	LOADING_TIMEOUT,
	TOKEN_RETRIEVED,
	COMPRESSING,
}
